In [1]:
#imbd data set

In [2]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('/Users/anishgulhane/Downloads/datasets after 14 sept/IMDB Dataset.csv')

In [4]:
df.shape

(50000, 2)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.value_counts()

review                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sentiment
Loved today's show!!! It was a variety and not solely cooking (which would have been great too). Very stimulating and captivating, always keeping the viewer peeking around the corner to see what was coming up next. She is as down to earth and as personable as you get, like one of us which made the show all the more enjoyable. Special guests, who are friends as well made for a nice surprise too. Loved the 'first' theme and that the audience was invited to play along too. I must admit I was shocked to see her come in under her time limits on a few things, but she did it and by golly I'll be writing those recipes down. Saving time in the kitchen means more time with family. Those who haven't tuned in yet, find out what channel and the time, I assure you that you won't be disappointed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    positive     5
Hilarious, clean, light-hearted, and quote-worthy. What else can you ask for in a film? This is my all-time, number one favorite movie. Ever since I was a little girl, I've dreamed of owning a blue van with flames and an observation bubble.<br /><br />The cliché characters in ridiculous situations are what make this film such great fun. The wonderful comedic chemistry between Stephen Furst (Harold) and Andy Tennant (Melio) make up most of my favorite parts of the movie. And who didn't love the hopeless awkwardness of Flynch? Don't forget the airport antics of Leon's cronies, dressed up as Hari Krishnas: dancing, chanting and playing the tambourine--unbeatable! The clues are genius, the locations are classic, and the plot is timeless.<br /><br />A word to the wise, if you didn't watch this film when you were little, it probably won't win a place in your heart today. But nevertheless give it a chance, you may find that "It doesn't matter what you say, it doesn't matter what you do, you've gotta play."                                                                                                                                                                                                                                                                                                      positive     4
How has this piece of crap stayed on TV this long? It's terrible. It makes me want to shoot someone. It's so fake that it is actually worse than a 1940s sci-fi movie. I'd rather have a stroke than watch this nonsense. I remember watching it when it first came out. I thought, hey this could be interesting, then I found out how absolutely, insanely, ridiculously stupid it really was. It was so bad that I actually took out my pocket knife and stuck my hand to the table.<br /><br />Please people, stop watching this and all other reality shows, they're the trash that is jamming the networks and canceling quality programming that requires some thought to create.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    negative     3
When i got this movie free from my job, along with three other similar movies.. I watched then with very low expectations. Now this movie isn't bad per se. You get what you pay for. It is a tale of love, betrayal, lies, sex, scandal, everything you want in a movie. Definitely not a Hollywood blockbuster, but for cheap thrills it is not that bad. I would probably never watch this movie again. In a nutshell this is the kind of movie that you would see either very late at night on a local television station that is just wanting to take up some time, or you would see it on a Sunday afternoon on a local television station that is trying to take up some time. Despite the bad acting, cliché lines, and sub par camera work. I didn't have the desire to turn off the movie and pretend like it never popped into my DVD player. The story has been done many times in many movies. This one is no different, no better, no worse. <br /><br />Just your average movie.                                                                                                                                                                                                                                                                                                                                                             negative     3
This show comes up with interesting locations as fast as the travel channel. It is billed as reality but in actuality it is pure prime time soap opera. It's tries to use exotic locales as a facade to bring people into a phony contest & then proceeds to hook viewers on the contestants soap opera style.<br /><br />It also borrows from an early CBS game show pioneer- Beat The Clock- by inventing situations for its contestants to try & overcome. Then it rewards the winner money. If they can spice it up with a little interaction between the characters, even better. While the game format is in slow motion versus Beat The Clock- the real accomplishment of this series is to escape reality. <br /><br />This show has elements of several types of successful past programs. Reality television, hardly, but if your hooked on the contestants, locale or contest, this is your cup of tea. If your not, this entire series is as I say, drivel dripping with gravy. It is another show hiding behind the reality label which is the trend it started in 2000.<br /><br />It is slick & well produced, so it might last a while yet. After all, so do re-runs of Gilligan's Island, Green Acres, The Beverly Hillbillies & The Brady Bunch. This just doesn't employ professional actors. The intelligence level is about the same.  negative     3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
I literally ran to watch it, expecting a film that will make me cry, or touch my heart.<br /><br />What I found was not heart-rending, but a lame exploitation of 1 strong human character.<br /><br />Interwined between a pair of young lesbians and an obese man.<br /><br />In a setting that is substantially devoid of sound not to mention acting of the most common.<br /><br />It was not entirely BAD, as I have seen worst - and I left the cinema $10 poorer but wiser - that a FILM well advertised is not the same as a FILM WELL-MADE.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       negative     1
I live and work in Lexington, Kentucky, the town where Zombie Planet was filmed. I'd heard about the film forever ago, from various people who claimed to be a critical part of the production. Then, for several years, I heard absolutely nothing. Imagine my surprise when I found it sitting all by itself at the local video store, just itching for a rental. So, being the cinephile that I am, I decided to give these local filmmakers a shot.<br /><br />Bad idea.<br /><br />Zombie Planet is overlong, boring, poorly acted, miserably shot -- and that's just the good stuff. I tried my hardest to enjoy it, which included removing my brain and setting it on the table so that it wouldn't get in the way of the horrible storyline. Alas, nothing worked. Zombie Planet is so bad it's pathetic. And the very idea that they're planning a sequel leads me to believe that the director and his henchmen have listened to none of the criticisms I'm sure they've heard. Move on, you guys. Please. In fact, refrain from film-making altogether. Or attend a few classes on pacing, storytelling, and, well, basic direction.<br /><br />Otherwise, for the love of God, hang it up.                                                                                                                                                     negative     1
I live in Mexico City, so I have to suffer throug the trailers for every piece of trash that comes out from all these stupid Mexican filmmakers. You want to admire a Mexican guy for making great films? Take a look at something by Guillermo del Toro (specially The Devil's Backbone), or maybe Alfonso Cuarón (though I really don't like his films, but I respect them).<br /><br />Mexican filmmakers often produce some of the most terrible utter trash ever (Por la Libre, El Segundo Aire, American Visa), but this is one of the lowest points in Mexican films ever. If you respect your brain, please avoid this piece of **** at all costs. It would be more intelligent to watch some video of a wedding or to watch Britney's reality show. That's got more IQ than everyone in this 'film'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               negative     1
I live in Missouri, so the direct effects of terrorism are largely unknown to me, this brought it home. That two men would put themselves on the line in the way that those members of FDNY and NYPD did, just to document the horror that unfolded on that day. This film is a testament to those who lost their lives and the true evil that terror brings.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               positive     1
ý thýnk uzak ýs the one of the best films of all times and everybody must realize this movie.I m a Turkish boy and a big cinema fun. and in this days our cinema industry is highing up.And UZAK is the best Turkish film of last ten years.and maybe one of the best films of all times.director nuri bilge ceylan is quite amazing.telling story,characters,atmosphere is wonderful.he is a minimalist director and tells about routine event family,dreams,expects,life.tells about you ,tells about me,tells about us.I promise you will find a piece of your body in this movie.cinema life welcomes a new director.he is waiting to realize.I promise yo you will love this movie please watch it                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     positive     1
Name: count, Length: 49582, dtype: int64

In [9]:
df = df.rename(columns = {'sentiment': 'Y','review': 'X'})

In [10]:
df.head()

                                                   X         Y
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
import nltk #  natural language tool kit (library used in NLP)
from nltk.corpus import stopwords

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [14]:
len(stopwords.words('english'))

198

In [15]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
df['X'] = df['X'].str.lower()

In [17]:
l1 = stopwords.words(('english'))
def text_process(mess):
    """
    1. remove the punctuation 
    2. remove the stopwords
    3. return the list of clean textwords
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)

    return[ word for word in nopunc.split() if word not in l1 ]

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a ID/token number to each word

In [19]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(df["X"])

In [20]:
len(bow_transformer.vocabulary_)

181543

In [21]:
tdm = bow_transformer.transform(df['X'])

In [22]:
tdm.shape

(50000, 181543)

In [23]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [24]:
df.head()

                                                   X         Y
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [25]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y)

from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.map({'positive': 1, 'negative': 0})
test_y = test_y.map({'positive': 1, 'negative': 0})

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [26]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build

LogisticRegression()

In [27]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[5465  759]
 [ 669 5607]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88      6224
           1       0.88      0.89      0.89      6276

    accuracy                           0.89     12500
   macro avg       0.89      0.89      0.89     12500
weighted avg       0.89      0.89      0.89     12500

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(
    accuracy_score(test_y, pred),
    " ",
    recall_score(test_y, pred, average='weighted'),
    " ",
    precision_score(test_y, pred, average='weighted'))

[[4560 1664]
 [1700 4576]]
0.73088   0.73088   0.7308941086261982

In [29]:
from  sklearn.ensemble import RandomForestClassifier
dt = RandomForestClassifier(oob_score=True)
dt.fit(train_x,train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(accuracy_score(test_y, pred))

[[5343  881]
 [ 948 5328]]
0.85368

In [30]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer # function
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [31]:
sent = SentimentIntensityAnalyzer()

In [36]:
df.shape

(50000, 2)

In [38]:
df

                                                       X         Y
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [39]:
score_list = []

for i  in range (0, df.shape[0]):
    score= sent.polarity_scores(df['X'][i])
    score_list.append(score['compound'])

In [40]:
score_list

[-0.9947,
 0.9641,
 0.9605,
 -0.9213,
 0.9744,
 0.9828,
 0.9022,
 0.8596,
 0.2362,
 0.9149,
 0.9482,
 0.5223,
 -0.968,
 0.3425,
 0.6168,
 -0.7488,
 0.3506,
 -0.9868,
 0.6518,
 0.945,
 0.5425,
 -0.9724,
 0.7948,
 0.9343,
 -0.7602,
 0.954,
 0.9962,
 -0.7964,
 -0.9208,
 -0.987,
 -0.9907,
 -0.6468,
 -0.9604,
 0.9971,
 0.7133,
 -0.9399,
 -0.962,
 -0.9847,
 0.9838,
 0.9797,
 0.0854,
 0.9858,
 -0.4678,
 0.9818,
 0.9182,
 0.9401,
 0.9165,
 -0.68,
 -0.7114,
 0.2152,
 0.9396,
 0.9893,
 -0.9274,
 0.7416,
 -0.968,
 -0.4417,
 -0.9477,
 0.7648,
 -0.7839,
 0.992,
 0.9139,
 -0.3699,
 0.7747,
 -0.168,
 -0.6149,
 0.5004,
 -0.6416,
 0.9902,
 0.63,
 0.9422,
 0.9837,
 0.9852,
 0.6441,
 0.9813,
 0.9382,
 0.9847,
 -0.8963,
 -0.9973,
 0.4082,
 0.8498,
 0.9714,
 -0.9406,
 -0.8837,
 0.5907,
 -0.8489,
 -0.9123,
 -0.1012,
 -0.7366,
 -0.7228,
 -0.9659,
 0.9311,
 -0.0516,
 0.9943,
 0.9818,
 0.9272,
 0.9826,
 -0.9434,
 -0.9844,
 -0.984,
 0.9831,
 0.8956,
 0.9444,
 0.9437,
 -0.4877,
 -0.9497,
 0.9865,
 0.9701,
 -0.9885,
 0.9761,
 0.9566,
 -0.9668,
 -0.214,
 0.6672,
 0.8133,
 0.9628,
 0.078,
 0.9806,
 -0.9439,
 -0.8472,
 0.955,
 -0.4493,
 0.9874,
 0.7096,
 -0.9219,
 -0.5346,
 0.7715,
 0.9724,
 -0.4678,
 0.9953,
 0.62,
 0.9897,
 0.9852,
 -0.5134,
 -0.8395,
 0.7071,
 0.9854,
 0.8385,
 0.5112,
 0.9868,
 0.8848,
 -0.9914,
 -0.9621,
 -0.9878,
 0.3274,
 -0.9853,
 0.9891,
 -0.8009,
 0.974,
 -0.2322,
 -0.0722,
 0.9881,
 0.8122,
 -0.667,
 0.9806,
 -0.9406,
 0.5528,
 0.9941,
 0.9918,
 0.9106,
 0.9411,
 0.9914,
 -0.9501,
 -0.9627,
 0.9924,
 0.9956,
 -0.7463,
 0.9757,
 -0.9591,
 -0.8141,
 0.9537,
 0.3246,
 0.9589,
 0.9955,
 0.9955,
 -0.9979,
 -0.9727,
 0.5916,
 -0.9973,
 0.9939,
 -0.9466,
 0.9633,
 -0.8284,
 0.9927,
 -0.8865,
 0.765,
 0.982,
 0.9968,
 -0.7589,
 0.9372,
 -0.997,
 -0.9788,
 0.992,
 0.9674,
 0.9523,
 -0.8784,
 -0.9482,
 0.9221,
 0.1227,
 0.989,
 0.9245,
 0.9348,
 0.9634,
 0.9963,
 0.9763,
 -0.9918,
 0.9788,
 -0.9146,
 -0.8958,
 0.8211,
 0.9088,
 0.9992,
 0.1561,
 0.8598,
 -0.7193,
 0.9458,
 0.9904,
 -0.6833,
 -0.859,
 0.9962,
 0.9477,
 -0.6486,
 0.9775,
 0.9986,
 -0.9539,
 0.9929,
 0.8242,
 -0.7684,
 0.9795,
 -0.9961,
 0.9377,
 -0.4848,
 0.8126,
 0.9906,
 0.9221,
 -0.5495,
 0.9218,
 0.9538,
 -0.9123,
 -0.8335,
 -0.6419,
 -0.2113,
 0.8907,
 -0.9644,
 0.4283,
 0.886,
 0.9501,
 -0.9983,
 -0.9445,
 0.9873,
 0.015,
 -0.9694,
 -0.7917,
 0.9844,
 -0.992,
 0.9767,
 0.9502,
 -0.6993,
 -0.539,
 0.9907,
 0.938,
 0.9941,
 0.9155,
 -0.9278,
 0.9952,
 -0.8934,
 0.967,
 -0.9742,
 -0.9949,
 0.7854,
 0.7875,
 0.9084,
 0.982,
 -0.9516,
 -0.9681,
 -0.5185,
 0.9318,
 -0.9965,
 -0.88,
 -0.9907,
 0.5093,
 0.9554,
 -0.9919,
 -0.973,
 -0.9887,
 0.2708,
 -0.9686,
 -0.9911,
 0.9657,
 0.9945,
 0.9728,
 0.9894,
 0.9501,
 0.9369,
 0.8179,
 0.9904,
 -0.5874,
 -0.9867,
 0.9979,
 0.9751,
 0.8992,
 0.9291,
 -0.937,
 0.9877,
 0.9707,
 0.9802,
 0.9795,
 0.9936,
 -0.6894,
 0.2185,
 0.8314,
 0.9988,
 0.0419,
 0.5775,
 0.7008,
 0.9172,
 0.4063,
 0.8561,
 0.8422,
 0.9772,
 0.9731,
 0.9894,
 0.9836,
 -0.9982,
 0.9514,
 -0.8654,
 0.9836,
 0.6425,
 -0.1166,
 0.9744,
 0.9432,
 -0.9248,
 0.6986,
 0.9977,
 0.9741,
 -0.9853,
 -0.9537,
 0.9311,
 0.9635,
 -0.9765,
 -0.9636,
 -0.917,
 0.9856,
 0.8176,
 -0.971,
 -0.7436,
 -0.9095,
 0.9623,
 0.9144,
 0.5328,
 0.8804,
 0.9232,
 0.8555,
 0.5006,
 -0.9978,
 0.5505,
 -0.9726,
 0.987,
 0.9794,
 0.296,
 0.5349,
 -0.8887,
 -0.984,
 0.8231,
 0.999,
 0.9976,
 0.9788,
 -0.726,
 -0.9365,
 -0.6386,
 0.9004,
 0.8409,
 0.9839,
 0.124,
 0.0649,
 -0.9964,
 0.9612,
 0.729,
 0.8395,
 0.9974,
 -0.9685,
 -0.7128,
 0.992,
 0.9042,
 -0.8225,
 0.6616,
 0.9856,
 0.8036,
 0.4959,
 0.296,
 0.9121,
 0.9849,
 0.2861,
 0.8519,
 0.9907,
 0.8641,
 0.4761,
 -0.7462,
 0.9659,
 -0.9799,
 0.9672,
 0.9967,
 0.8976,
 0.8535,
 0.9579,
 0.9134,
 0.8627,
 0.9812,
 0.9698,
 -0.9774,
 0.9686,
 0.9996,
 0.8841,
 0.8983,
 -0.8316,
 0.981,
 -0.2533,
 0.9696,
 0.617,
 -0.944,
 0.9557,
 0.99,
 -0.5859,
 -0.8676,
 0.9898,
 0.3537,
 0.9772,
 0.9393,
 0.9939,
 -0.9857,
 0.994,
 -0.9578,
 -0.9969,
 -0.9303,
 0.9971,
 -0.7377,
 0.9785,
 0.9509,
 0.4723,
 0.9589,
 0.9638,
 -0.9619,
 0.9485,
 0.9695,
 -0.1496,
 -0.6794,
 0.9884,
 -0.837,
 0.9896,
 0.706,
 -0.8016,
 0.9879,
 -0.5562,
 -0.9209,
 0.471,
 -0.9649,
 0.9796,
 -0.9994,
 0.9638,
 0.5794,
 -0.9345,
 -0.8658,
 0.9905,
 0.7422,
 0.7108,
 -0.9598,
 -0.9698,
 0.9928,
 0.9862,
 -0.5574,
 0.9545,
 0.9708,
 -0.9348,
 -0.9299,
 0.5727,
 0.25,
 0.9927,
 0.98,
 -0.9731,
 0.2563,
 0.9961,
 -0.6831,
 -0.8581,
 0.1212,
 0.4782,
 0.9867,
 -0.9943,
 -0.9488,
 0.9983,
 -0.122,
 -0.9964,
 0.8832,
 0.3182,
 0.9834,
 0.9705,
 0.9934,
 -0.9402,
 0.4257,
 0.7671,
 -0.9929,
 0.9983,
 0.9869,
 0.8883,
 0.9684,
 -0.837,
 0.9895,
 0.9557,
 0.8168,
 0.9763,
 -0.4079,
 0.6405,
 0.7131,
 -0.942,
 0.6428,
 0.9702,
 0.8914,
 0.9864,
 -0.7184,
 0.9822,
 -0.8169,
 -0.996,
 0.8909,
 0.9593,
 0.8739,
 -0.9974,
 -0.4215,
 -0.9569,
 0.8847,
 0.6454,
 -0.9351,
 -0.9647,
 -0.7613,
 0.8268,
 0.9668,
 0.4149,
 -0.5953,
 -0.9876,
 -0.9898,
 -0.8415,
 0.9794,
 0.9975,
 0.9284,
 -0.8613,
 -0.8858,
 -0.8995,
 0.9943,
 -0.5085,
 0.7858,
 0.9759,
 -0.9824,
 0.765,
 0.828,
 0.8118,
 0.9142,
 0.743,
 -0.9827,
 0.0788,
 0.8475,
 -0.7021,
 0.9876,
 -0.9882,
 -0.3126,
 0.9922,
 -0.7619,
 -0.8415,
 0.9601,
 -0.1792,
 0.9995,
 -0.9719,
 0.9326,
 -0.8056,
 0.9801,
 0.9719,
 0.9951,
 0.9116,
 -0.9283,
 -0.45,
 0.5979,
 -0.9951,
 -0.3222,
 0.8225,
 0.973,
 0.9906,
 0.9635,
 -0.185,
 0.9307,
 0.9768,
 0.8819,
 -0.9195,
 0.9384,
 -0.9837,
 0.9961,
 -0.9853,
 0.9947,
 0.9736,
 -0.2924,
 0.9705,
 0.4677,
 0.9968,
 0.9782,
 0.664,
 0.4632,
 0.9884,
 0.9738,
 -0.7202,
 0.7452,
 0.9187,
 0.8174,
 0.8893,
 0.9977,
 0.9834,
 0.9073,
 -0.9835,
 -0.7664,
 -0.9541,
 0.4854,
 -0.9476,
 0.9895,
 -0.9493,
 -0.9941,
 0.9505,
 0.9901,
 0.9594,
 0.9722,
 -0.9511,
 -0.9014,
 -0.9155,
 0.9591,
 -0.9003,
 -0.9618,
 0.3486,
 0.296,
 0.9926,
 0.9932,
 0.7428,
 0.9651,
 -0.97,
 -0.6185,
 -0.9246,
 0.8957,
 0.1531,
 -0.0772,
 0.9846,
 -0.9529,
 0.9931,
 -0.7046,
 -0.5993,
 -0.9571,
 0.9855,
 0.965,
 -0.9981,
 0.9847,
 0.5913,
 -0.8902,
 0.9761,
 -0.9944,
 0.3048,
 0.9899,
 0.8473,
 0.9845,
 -0.1462,
 -0.7195,
 0.9816,
 0.9923,
 0.9938,
 0.9968,
 0.875,
 0.6369,
 0.9629,
 -0.8464,
 0.9889,
 0.9424,
 -0.3611,
 0.9953,
 -0.7058,
 -0.8815,
 -0.8622,
 0.9226,
 0.8231,
 0.9406,
 -0.9891,
 0.8927,
 -0.4152,
 0.978,
 -0.3291,
 -0.9915,
 0.8261,
 0.9787,
 -0.9848,
 -0.9284,
 0.9759,
 -0.908,
 0.9237,
 0.9648,
 0.9977,
 0.9609,
 -0.9815,
 -0.724,
 0.983,
 0.8206,
 0.9711,
 -0.698,
 0.9594,
 0.9765,
 0.9926,
 -0.571,
 0.9551,
 0.9879,
 0.9876,
 0.9424,
 0.9531,
 0.9891,
 0.6506,
 0.9983,
 -0.8836,
 0.9962,
 -0.818,
 0.8922,
 -0.9559,
 0.9427,
 0.9345,
 0.9853,
 -0.8798,
 0.9909,
 0.998,
 0.9773,
 0.0065,
 0.981,
 0.2962,
 -0.9298,
 -0.099,
 0.9587,
 -0.2084,
 0.7524,
 0.9013,
 0.986,
 0.6588,
 -0.9947,
 -0.1957,
 -0.9076,
 0.9038,
 -0.2952,
 0.9884,
 -0.5945,
 0.6053,
 -0.8415,
 0.9324,
 0.9912,
 0.9956,
 -0.9738,
 0.9905,
 0.9675,
 -0.9783,
 0.6073,
 0.855,
 -0.6082,
 -0.8402,
 -0.7994,
 -0.9494,
 -0.9168,
 -0.9244,
 0.9497,
 -0.5285,
 -0.9649,
 -0.9657,
 -0.9189,
 -0.9984,
 0.7008,
 -0.3146,
 -0.6603,
 -0.9704,
 -0.8536,
 -0.5413,
 0.9674,
 0.9907,
 -0.9527,
 0.9565,
 -0.4678,
 0.8679,
 0.7516,
 0.9829,
 0.8041,
 0.9893,
 0.8795,
 -0.9881,
 -0.9571,
 0.3471,
 0.002,
 0.891,
 0.8272,
 0.25,
 0.9622,
 0.6844,
 0.9911,
 0.7873,
 -0.9001,
 0.9905,
 0.9063,
 0.9907,
 -0.9822,
 -0.7975,
 0.8903,
 0.7557,
 0.9901,
 0.9772,
 0.9893,
 -0.9661,
 0.9746,
 0.845,
 0.9089,
 -0.7126,
 0.9315,
 0.9904,
 0.9345,
 0.3912,
 0.989,
 0.8474,
 0.9941,
 0.9571,
 0.9741,
 0.9657,
 0.9787,
 0.5124,
 0.9793,
 0.9766,
 -0.9984,
 0.9953,
 0.9732,
 0.9312,
 -0.9963,
 -0.8658,
 0.9939,
 0.9209,
 0.9979,
 -0.9132,
 -0.9283,
 -0.4497,
 0.9934,
 0.9708,
 0.7657,
 -0.7664,
 0.9792,
 -0.9901,
 0.9824,
 -0.6504,
 0.9176,
 0.9822,
 0.9655,
 -0.8521,
 -0.1934,
 0.9707,
 -0.5886,
 -0.9806,
 0.9887,
 0.9396,
 0.4567,
 0.983,
 -0.6199,
 -0.7461,
 0.9985,
 -0.9785,
 0.2183,
 0.9949,
 -0.8992,
 0.875,
 0.7841,
 -0.9752,
 0.9911,
 0.9793,
 0.9615,
 -0.9225,
 0.4855,
 -0.5339,
 -0.9377,
 0.9715,
 0.9975,
 -0.6457,
 0.9675,
 0.6812,
 0.9634,
 -0.9957,
 -0.9709,
 -0.9234,
 -0.3472,
 -0.5815,
 0.9816,
 -0.9841,
 -0.9009,
 0.9832,
 0.9446,
 0.8785,
 0.839,
 0.9837,
 0.9818,
 0.4815,
 0.9928,
 0.7139,
 0.9864,
 0.9667,
 0.9954,
 -0.5442,
 0.9175,
 0.6573,
 0.2876,
 -0.9346,
 0.7362,
 -0.8924,
 0.9231,
 0.9581,
 0.9834,
 0.973,
 -0.7293,
 0.8556,
 -0.9893,
 0.9547,
 0.8934,
 0.9647,
 -0.3367,
 0.9599,
 -0.959,
 -0.9745,
 0.9962,
 0.3563,
 0.2023,
 0.9895,
 0.9844,
 0.9145,
 0.5181,
 0.9206,
 0.9842,
 0.8334,
 0.9911,
 -0.9183,
 -0.7834,
 -0.9108,
 0.9819,
 0.9719,
 0.5189,
 0.8834,
 -0.9876,
 0.9789,
 -0.0763,
 0.97,
 -0.9514,
 0.9991,
 0.9875,
 -0.9853,
 0.9862,
 0.9574,
 0.9245,
 -0.83,
 0.9825,
 0.9742,
 0.9801,
 0.6124,
 0.9778,
 0.922,
 0.2263,
 0.985,
 0.2033,
 0.1561,
 0.9391,
 0.985,
 0.9915,
 0.5707,
 0.9641,
 -0.9539,
 -0.6757,
 0.8682,
 0.8463,
 -0.7326,
 -0.9937,
 0.995,
 0.996,
 0.5372,
 -0.9166,
 -0.2269,
 0.7931,
 -0.9851,
 0.9962,
 -0.9937,
 -0.6563,
 -0.8949,
 -0.9622,
 0.9407,
 0.9784,
 0.9973,
 0.9533,
 0.9287,
 0.9879,
 -0.3335,
 0.2732,
 -0.9667,
 0.9165,
 0.8798,
 0.8885,
 -0.3676,
 -0.9618,
 -0.993,
 0.1838,
 0.5413,
 ...]

In [41]:
score_list = pd.DataFrame(score_list)

In [42]:
score_list.describe()

                  0
count  50000.000000
mean       0.298625
std        0.805933
min       -0.999800
25%       -0.690000
50%        0.819300
75%        0.970400
max        0.999900